// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: user_service_grpc/user_service.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserServiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceReq) Reset() {
	*x = UserServiceReq{}
	mi := &file_user_service_grpc_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceReq) ProtoMessage() {}

func (x *UserServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_grpc_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceReq.ProtoReflect.Descriptor instead.
func (*UserServiceReq) Descriptor() ([]byte, []int) {
	return file_user_service_grpc_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserServiceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserServiceReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserServiceReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserServiceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceRes) Reset() {
	*x = UserServiceRes{}
	mi := &file_user_service_grpc_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceRes) ProtoMessage() {}

func (x *UserServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_grpc_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceRes.ProtoReflect.Descriptor instead.
func (*UserServiceRes) Descriptor() ([]byte, []int) {
	return file_user_service_grpc_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserServiceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_service_grpc_user_service_proto protoreflect.FileDescriptor

const file_user_service_grpc_user_service_proto_rawDesc = "" +
	"\n" +
	"$user_service_grpc/user_service.proto\x12\fuser_service\"V\n" +
	"\x0eUserServiceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"*\n" +
	"\x0eUserServiceRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2U\n" +
	"\vUserService\x12F\n" +
	"\x06Signup\x12\x1c.user_service.UserServiceReq\x1a\x1c.user_service.UserServiceRes\"\x00B3Z1github.com/banisys/user-service/proto/user;userpbb\x06proto3"

var (
	file_user_service_grpc_user_service_proto_rawDescOnce sync.Once
	file_user_service_grpc_user_service_proto_rawDescData []byte
)

func file_user_service_grpc_user_service_proto_rawDescGZIP() []byte {
	file_user_service_grpc_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_grpc_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_grpc_user_service_proto_rawDesc), len(file_user_service_grpc_user_service_proto_rawDesc)))
	})
	return file_user_service_grpc_user_service_proto_rawDescData
}

var file_user_service_grpc_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_service_grpc_user_service_proto_goTypes = []any{
	(*UserServiceReq)(nil), // 0: user_service.UserServiceReq
	(*UserServiceRes)(nil), // 1: user_service.UserServiceRes
}
var file_user_service_grpc_user_service_proto_depIdxs = []int32{
	0, // 0: user_service.UserService.Signup:input_type -> user_service.UserServiceReq
	1, // 1: user_service.UserService.Signup:output_type -> user_service.UserServiceRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_grpc_user_service_proto_init() }
func file_user_service_grpc_user_service_proto_init() {
	if File_user_service_grpc_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_grpc_user_service_proto_rawDesc), len(file_user_service_grpc_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_grpc_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_grpc_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_grpc_user_service_proto_msgTypes,
	}.Build()
	File_user_service_grpc_user_service_proto = out.File
	file_user_service_grpc_user_service_proto_goTypes = nil
	file_user_service_grpc_user_service_proto_depIdxs = nil
}
